name: "moritan_bot"
name_debug: 

oauth:
  consumer_key: 
  consumer_secret: 
  oauth_token: 
  oauth_token_secret: 

oauth_debug:
  consumer_key: 
  consumer_secret: 
  oauth_token: 
  oauth_token_secret: 

ssh:
  :username: 
  :opt:
    :password: 
    :port: 22

ReplayTable:
  self:
    - !ruby/regexp /(moritan|もりたん)(bot|ぼっと|ボット)?/i
    - ["はい","なんですか"]
  call:
    - !ruby/regexp /^(moritan|もりたん)(bot|ぼっと|ボット)?$/i
    - ["はい","なんですか"]

  mention:
    - 
      - ["ありがと","さんくす",!ruby/regexp /(thank|thx)/i]
      - ["どういたしまして","いえいえ"]
    - 
      - [!ruby/regexp /yo/i]
      - ["Yo"]
    - 
      - ["ただいま","きたく","帰宅"]
      - ["おかえりなさい","おかえり"]
    - 
      - ["こんばんは","こんばんわ"]
      - ["こんばんは"]
    - 
      - ["こんにちは"]
      - ["こんにちは"]
    - 
      - ["おはよ",!ruby/regexp /(お|起)きた/]
      - ["おはようございます","おはよう"]
    - 
      - ["おやすみ",!ruby/regexp /(寝|ね)(る|ます)/,"ねむい","眠い"]
      - ["おやすみなさい"]
    - 
      - ["本当","ホント","ほんとう","うそ","嘘"]
      - ["本当です","嘘じゃないです"]
    - 
      - ["えらい","偉い","てんさい","天才","すごい","あたまいい","頭いい"]
      - ["当然です","当たり前です"]
    - 
      - ["ようじょ","幼女"]
      - ["ぅゎょぅι゛ょっょぃ"]
    - 
      - ["進捗","しんちょく"]
      - ["進捗はありましたか","進捗どうですか"]
    - 
      - ["死ね","しね"]
      - ["生きます"]
    - 
      - ["生きてる","死んでる"]
      - ["生きてます"]
    - 
      - ["おい","あの","もしもし"]
      - ["なんですか","何かごようですか"]
    - 
      - [!ruby/regexp /ping/i]
      - ["pong"]
    - 
      - ["使い方","ヘルプ",!ruby/regexp /help/i]
      - ["使い方はこちらを参考にしてください https://sites.google.com/site/moritanbot/home"]

  terms: ["上への写像","解空間","階数","固有値","逆行列","階段行列","拡大係数行列",
          "基底","基本行列","逆元","グラム・シュミット","クラメルの公式","クロネッカーのデルタ",
          "係数行列","固有空間","固有ベクトル","三角行列","実線形空間","写像",
          "ジョルダン細胞","ジョルダンの標準形","スカラー","正規化","正規直交基底",
          "正則","成分","正方行列","線形結合","線形従属","線形独立","対角化可能",
          "対角行列","同形写像","ノルム","掃き出し","ハミルトン・ケーリーの定理","張る空間",
          "表現行列","複素線形空間","フロベニゥスの定理","ベクトル空間","ユニタリ行列",
          "ユニタリ空間","余因子行列","零行列",]

Function:
  api_key: 

  error_message:
    not_regular: "正則行列じゃないです"
    not_square: "正方行列じゃないです"
    not_hermitian: "成分に虚数を含む行列の固有値計算はエルミート行列のみ対応しています"
    invalid_format: |
      
      フォーマットが違います
      使い方はこちらを参照してください
      https://sites.google.com/site/moritanbot/home
